{
  "hash": "8fac4056cfbc919e131cbdf2f39f29a2",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"MNIST\"\nsubtitle: \"70,000 handwritten digits, 28×28 pixel vectors, k=10 ground truth.\"\norder: 2\nimage: mnist_files/figure-html/fig-dyf-output-1.png\ncategories: [images, large, pixels]\ntrue-k: 10\nformat:\n  html:\n    code-fold: show\n    code-tools: true\nexecute:\n  warning: false\n  message: false\n---\n\nThe scaled-up version of [Digits](digits.qmd). Same domain, same task, same `k=10` — but 40× more samples and 12× higher pixel dimensionality. Does DYF's parameter-free story survive the jump in scale, or does it fall apart under a heavier load?\n\nShort answer, as we'll see: it gets *better* with scale. On Digits, oracle k-means beat DYF on both metrics. On MNIST, DYF — told nothing — recovers 12 communities for 10 classes and beats oracle k-means on both AMI and ARI. The reason is worth understanding, because it is the same reason DYF under-performs on the small dataset.\n\n## Load MNIST\n\n::: {#load .cell execution_count=1}\n``` {.python .cell-code}\nimport os\nimport numpy as np\n\nCACHE = \"/tmp/gallery_mnist.npz\"\nif os.path.exists(CACHE):\n    z = np.load(CACHE)\n    X, y = z[\"X\"], z[\"y\"]\nelse:\n    from sklearn.datasets import fetch_openml\n    m = fetch_openml(\"mnist_784\", version=1, as_frame=False, parser=\"auto\")\n    X = (m.data.astype(np.float32) / 255.0)   # normalize pixels to [0, 1]\n    y = m.target.astype(int)\n    np.savez(CACHE, X=X, y=y)\n\nprint(f\"{X.shape[0]:,} samples, {X.shape[1]}d, true k = {len(set(y))}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n70,000 samples, 784d, true k = 10\n```\n:::\n:::\n\n\n## Run DYF\n\n::: {#run-dyf .cell execution_count=2}\n``` {.python .cell-code}\nimport sys\nsys.path.insert(0, \".\")\nfrom _gallery import run_dyf_cached, run_kmeans, plot_single, metrics_table\n\nresult = run_dyf_cached(X, y, cache_path=\"/tmp/gallery_mnist_dyf.npz\")\nprint(f\"Recovered k: {result.recovered_k}  (true k = {result.true_k})\")\nprint(f\"AMI:         {result.ami:.3f}\")\nprint(f\"ARI:         {result.ari:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRecovered k: 12  (true k = 10)\nAMI:         0.546\nARI:         0.422\n```\n:::\n:::\n\n\n## Oracle k-means\n\n::: {#kmeans .cell execution_count=3}\n``` {.python .cell-code}\nkmeans = run_kmeans(X, y)\nprint(f\"k-means AMI={kmeans['ami']:.3f}, ARI={kmeans['ari']:.3f} (told k={result.true_k})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nk-means AMI=0.491, ARI=0.361 (told k=10)\n```\n:::\n:::\n\n\n## Figures\n\n::: {.gallery-fluid}\n\n::: {#cell-fig-truth .cell execution_count=4}\n``` {.python .cell-code}\nplot_single(result.umap_2d, y, title=f\"Ground truth (k={result.true_k})\")\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n![Ground truth — each of the 10 digit classes.](mnist_files/figure-html/fig-truth-output-1.png){#fig-truth width=470 height=470}\n:::\n:::\n\n\n::: {#cell-fig-dyf .cell execution_count=5}\n``` {.python .cell-code}\nplot_single(result.umap_2d, result.labels, title=f\"DYF (recovered k={result.recovered_k})\")\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n![DYF — parameter-free, no k supplied.](mnist_files/figure-html/fig-dyf-output-1.png){#fig-dyf width=470 height=470}\n:::\n:::\n\n\n::: {#cell-fig-kmeans .cell execution_count=6}\n``` {.python .cell-code}\nplot_single(result.umap_2d, kmeans[\"labels\"], title=f\"k-means (told k={result.true_k})\")\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n![K-means given the oracle k=10.](mnist_files/figure-html/fig-kmeans-output-1.png){#fig-kmeans width=470 height=470}\n:::\n:::\n\n\n:::\n\n## Metrics\n\n::: {#metrics .cell execution_count=7}\n``` {.python .cell-code}\nprint(metrics_table(result, kmeans, None))\n```\n| Method | Recovered k | AMI | ARI | % discarded | wall (s) |\n|--------|------------:|----:|----:|------------:|---------:|\n| **DYF** (parameter-free) | 12 | 0.546 | 0.422 | 0% | 8.19 |\n| k-means (oracle k=10) | 10 | 0.491 | 0.361 | 0% | 1.22 |\n\n*Wall time: DYF 8.19 s (tree build + index write + Louvain) vs k-means 1.22 s (one k-means++ init at the oracle k) — DYF 6.7× slower here. The shared UMAP layout is not counted for either.*\n:::\n\n\nThis is also the first page where the `wall (s)` column matters. DYF is the slower tool: a tree over 70,000 × 784 rows, a written index and a Louvain pass cost several times one k-means++ init at `k=10`. What that time buys is in the next two sections — a partition that beats the oracle, and a hierarchy under it that k-means cannot produce at any `k`. The regime where DYF is the *faster* tool is a different comparison: at 1.3M cells it matches a kNN-graph + Leiden pipeline's partition in a fraction of the time (dyf `KNOWN_ISSUES.md` #10), and that pipeline, not k-means, is what people run at that scale.\n\n## Deep dive: where do DYF's 12 clusters come from?\n\nTwelve clusters for ten digits is close enough to the label's own granularity that the interesting question is no longer \"why so many?\" but \"which two digits got split, and did anything get merged?\" This section answers both from the partition itself.\n\n### First, the statistical audit\n\nIf DYF's clusters track the digit classes, each should be dominated by one digit. Mixed bags are the signature of classes being merged.\n\n::: {#purity-audit .cell execution_count=8}\n``` {.python .cell-code}\nimport numpy as np\nfrom collections import Counter\n\nlabels = result.labels\nrows = []\nfor cid in sorted(set(labels)):\n    mask = labels == cid\n    n = int(mask.sum())\n    if n == 0:\n        continue\n    vals, cnts = np.unique(y[mask], return_counts=True)\n    rows.append({\"cid\": cid, \"n\": n, \"dominant\": int(vals[np.argmax(cnts)]),\n                 \"purity\": cnts.max() / n})\n\nr80 = sum(1 for r in rows if r[\"purity\"] > 0.80)\nr90 = sum(1 for r in rows if r[\"purity\"] > 0.90)\nr95 = sum(1 for r in rows if r[\"purity\"] > 0.95)\nweighted = sum(r[\"purity\"] * r[\"n\"] for r in rows) / sum(r[\"n\"] for r in rows)\n\ndigit_counts = Counter(r[\"dominant\"] for r in rows)\nper_digit = \", \".join(f\"{d}×{n}\" for d, n in sorted(digit_counts.items()))\n\nprint(f\"**{len(rows)} DYF clusters. Weighted purity: {weighted:.3f}.**\\n\")\nprint(f\"- {r80}/{len(rows)} clusters are >80% pure (dominated by one digit)\\n\")\nprint(f\"- {r90}/{len(rows)} are >90% pure\\n\")\nprint(f\"- {r95}/{len(rows)} are >95% pure\\n\")\nprint(f\"- Clusters per digit: {per_digit}\\n\")\n```\n**12 DYF clusters. Weighted purity: 0.643.**\n\n- 4/12 clusters are >80% pure (dominated by one digit)\n\n- 2/12 are >90% pure\n\n- 0/12 are >95% pure\n\n- Clusters per digit: 0×1, 1×1, 2×1, 3×2, 4×1, 5×1, 6×2, 7×1, 8×1, 9×1\n\n:::\n\n\nEvery digit has at least one cluster where it is the majority, so nothing was lost outright. But a weighted purity around two-thirds says several clusters are shared between digits. The next cell names them.\n\n### Split digits and merged digits\n\n::: {#split-merged .cell execution_count=9}\n``` {.python .cell-code}\nby_digit = {}\nfor r in rows:\n    by_digit.setdefault(r[\"dominant\"], []).append(r)\nsplit = {d: sorted(rs, key=lambda r: -r[\"n\"]) for d, rs in by_digit.items() if len(rs) > 1}\nmixed = sorted([r for r in rows if r[\"purity\"] < 0.6], key=lambda r: -r[\"n\"])\n\nprint(f\"**Digits split across more than one DYF cluster:** {', '.join(str(d) for d in sorted(split)) or 'none'}\\n\")\nfor d, rs in sorted(split.items()):\n    print(f\"- digit {d}: \" + \"; \".join(f\"cluster {r['cid']} (n={r['n']:,}, {r['purity']:.0%} {d}s)\" for r in rs) + \"\\n\")\n\nprint(f\"\\n**Clusters with no dominant digit (purity < 60%):** {len(mixed)}\\n\")\nfor r in mixed:\n    mask = labels == r[\"cid\"]\n    vals, cnts = np.unique(y[mask], return_counts=True)\n    order = np.argsort(-cnts)[:3]\n    print(f\"- cluster {r['cid']} (n={r['n']:,}): \" + \", \".join(f\"{int(vals[i])} {cnts[i] / r['n']:.0%}\" for i in order) + \"\\n\")\n\n# For the image grids below: the split digit whose two largest sub-clusters are purest.\nshow_digit = max(split, key=lambda d: min(r[\"purity\"] for r in split[d][:2])) if split else None\nshow_subs = split[show_digit][:2] if show_digit is not None else []\n```\n**Digits split across more than one DYF cluster:** 3, 6\n\n- digit 3: cluster 9 (n=5,968, 38% 3s); cluster 2 (n=5,813, 66% 3s)\n\n- digit 6: cluster 8 (n=4,643, 80% 6s); cluster 11 (n=3,899, 71% 6s)\n\n\n**Clusters with no dominant digit (purity < 60%):** 5\n\n- cluster 1 (n=8,160): 4 44%, 9 42%, 7 5%\n\n- cluster 3 (n=7,496): 9 34%, 7 32%, 4 28%\n\n- cluster 5 (n=6,696): 8 53%, 1 27%, 2 8%\n\n- cluster 9 (n=5,968): 3 38%, 5 29%, 8 24%\n\n- cluster 4 (n=4,722): 5 56%, 0 21%, 8 10%\n\n:::\n\n\nRead the two lists together. The two \"extra\" clusters are the digit 6 split into two near-equal halves, each about 80% pure — that is the split the pictures below examine. The digit 3 is also split, but one of its halves is really a 3/5/8 mixture. And the impurity has one dominant source: **4 and 9 are never separated** — they share two clusters, each roughly 40% fours and 40% nines — with 8-with-1 and 5-with-0 as smaller confusions. In pixel space a closed-top 4 and a 9 are a few pixels apart, so this is the classic MNIST confusion showing up as a merge rather than as misclassification. Nothing here is a class fragmented into arbitrary pieces; every decision is one the flat label cannot express, and the pictures decide whether the one clean split is sensible.\n\n### The split digit, as images\n\nThe digit below is the one DYF divided most cleanly into two communities. Each grid is a random sample from one of them:\n\n::: {.gallery-fluid}\n\n::: {#cell-fig-split-a .cell execution_count=10}\n``` {.python .cell-code}\nfrom _gallery import image_grid\nfig_a = None\nif len(show_subs) >= 1:\n    idx = np.where(result.labels == show_subs[0][\"cid\"])[0]\n    fig_a = image_grid(X, idx, title=f\"digit {show_digit}, DYF cluster {show_subs[0]['cid']} (n={show_subs[0]['n']:,})\")\nfig_a  # a bare expression displays; a call inside the `if` would not\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n![DYF sub-cluster A of the split digit — random sample.](mnist_files/figure-html/fig-split-a-output-1.png){#fig-split-a width=673 height=343}\n:::\n:::\n\n\n::: {#cell-fig-split-b .cell execution_count=11}\n``` {.python .cell-code}\nfig_b = None\nif len(show_subs) >= 2:\n    idx = np.where(result.labels == show_subs[1][\"cid\"])[0]\n    fig_b = image_grid(X, idx, title=f\"digit {show_digit}, DYF cluster {show_subs[1]['cid']} (n={show_subs[1]['n']:,})\")\nfig_b\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n![DYF sub-cluster B of the same digit — random sample.](mnist_files/figure-html/fig-split-b-output-1.png){#fig-split-b width=673 height=343}\n:::\n:::\n\n\n:::\n\nTwo ways of writing a 6. The first grid's sixes have a small, tight loop on a long stem, mostly thin and slanted; the second grid's have a large round loop and heavier strokes — and its impurities are 0s, which is what a big-looped 6 turns into when the stem shortens. It is a difference of loop size and stroke weight rather than two unmistakably different populations, so read it as a stylistic sub-community the ten-way label has no room for: modest, visible, and the kind of split a retrieval task would want kept. The caveats say how we'd test that properly.\n\n### The same digit, from k-means\n\nK-means was told `k=10`, so it gave us exactly ten clusters. Here's a random sample from the cluster that contains the most 7s:\n\n::: {#cell-fig-kmeans-sevens .cell execution_count=12}\n``` {.python .cell-code}\nkm_labels = kmeans[\"labels\"]\nbest_cid, best_count = -1, 0\nfor cid in np.unique(km_labels):\n    cnt = int(((km_labels == cid) & (y == 7)).sum())\n    if cnt > best_count:\n        best_count, best_cid = cnt, int(cid)\nidx = np.where(km_labels == best_cid)[0]\nimage_grid(X, idx, title=f\"k-means cluster {best_cid} (n={len(idx):,}, {best_count:,} are 7s)\")\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n![The k-means cluster that contains the most 7s.](mnist_files/figure-html/fig-kmeans-sevens-output-1.png){#fig-kmeans-sevens width=673 height=343}\n:::\n:::\n\n\nRead the title: the fraction of this cluster that is actually a 7. The rest are other digits — mostly 4s, 9s and 5s — that share a prominent diagonal stroke in pixel space. Committing to exactly ten Voronoi cells forced k-means to draw a boundary somewhere, and \"things with a diagonal stroke\" was the cleanest cut available. DYF spent its budget differently: it kept the digit classes apart and used two extra clusters on a style split. That is why it wins ARI here as well as AMI.\n\n### Why this matters\n\nIf your downstream task is **classification** (given a new image, predict 0–9), you want a ten-way partition — and on MNIST the one DYF finds without being told `k` is closer to the labels than the one k-means finds with it.\n\nIf your downstream task is **retrieval** (given a user's handwriting, find visually similar samples), the style split is the feature you want kept.\n\nIf your downstream task is **exploration** (what's in this corpus?), you want the hierarchy: start at the 12 communities, then walk down to 10 or 5 to see how they merge, without refitting.\n\n## Walking down the hierarchy\n\nDYF's 12 communities sit at the top of a partition hierarchy. `merge_to_max_k` collapses them to coarser granularities:\n\n::: {#merge-walk .cell execution_count=13}\n``` {.python .cell-code}\nfrom _gallery import merge_walk, merge_walk_table\n\nwalk = merge_walk(result, X, y, targets=[40, 20, 10, 5])\nprint(merge_walk_table(walk, result))\n```\n| Resolution     | Actual k | AMI   | ARI   |\n|----------------|---------:|------:|------:|\n| **Raw DYF**    | **12** | **0.546** | **0.422** |\n| merge → 40    |   12     | 0.546 | 0.422 |\n| merge → 20    |   12     | 0.546 | 0.422 |\n| merge → 10    |   10     | 0.500 | 0.363 |\n| merge → 5     |    5     | 0.399 | 0.275 |\n:::\n\n\nTargets above 12 are no-ops — there is nothing to merge. Merging to exactly 10 *costs* a little on both metrics, because the two extra clusters were a real split and forcing them back together is the wrong merge for this label. The raw partition is the best point on the walk. That is what \"recover `k` from the data\" looks like when it works: the finest natural partition is already at the label's granularity, and the walk is there for the tasks that want something coarser.\n\n## What happened to the Digits story?\n\nThe two datasets tell opposite stories, and the comparison is the most instructive table in the gallery:\n\n| Dataset   | DYF k  | k-means AMI | DYF AMI   | DYF − k-means AMI | DYF ARI   | k-means ARI |\n|-----------|-------:|------------:|----------:|------------------:|----------:|------------:|\n| Digits    | 8      | 0.773       | 0.668     | −0.105            | 0.536     | 0.726       |\n| **MNIST** | **12** | **0.491**   | **0.546** | **+0.055**        | **0.422** | **0.361**   |\n\nOn 1,797 digits DYF *under*-splits (8 communities for 10 classes) and loses on both metrics. On 70,000 it lands at 12 and wins on both. Same code, same defaults.\n\n### Why does scale help?\n\nDYF clusters leaf centroids, not points. On Digits the tree has around 190 leaves; a modularity optimiser on a graph that small hits its resolution limit and merges genuine classes — the well-known failure of modularity on small graphs, not a property of the digits. On MNIST the tree has about 3,200 leaves, the community graph is rich enough to resolve ten-plus communities, and the partition snaps to the label. The [Digits](digits.qmd) notebook shows the other side of this: raising the Louvain `resolution` to 2 recovers 10 communities there and beats the default on both metrics.\n\nSo the axis that matters is not sample count as such but **leaf count** — how many super-points the tree hands to community detection. Below a few hundred, expect under-splitting at the default resolution.\n\n### The sports analogy update\n\nDigits was k-means's home court — convex blobs, small `k`, oracle-provided, and a DYF that could not field enough players. It won cleanly.\n\nMNIST is the away game with a full roster. K-means still had the oracle, and still lost on both scoreboards — because knowing `k=10` does not tell you *where* to cut, and pixel space rewarded the cut that keeps digit classes apart over the one that hits exactly ten centers.\n\n## Caveats\n\n- **The two extra clusters need a look, not a number.** The grids above are the evidence. Our reading is that the split is stylistic (reading (a)); a rigorous version would test it by holding out the split digit and checking whether the two sub-clusters predict, say, writer identity or stroke width. The gallery skips that to keep the notebook readable.\n- **Earlier versions of this page reported 81–86 DYF clusters** and built an \"over-partitioning is hierarchy\" argument on them. That count was an artifact: the Louvain optimiser in `dyf-rs` before 0.12.0 ran a single level with no aggregation phase and could not merge communities once formed. The fix is documented in dyf's `KNOWN_ISSUES.md` (issue 10); the numbers on this page are from the corrected optimiser.\n- **UMAP is a projection, not the cluster space.** When DYF's and k-means's partitions look visually different in the UMAP panel, some of that is true clustering difference and some is UMAP's 2D compression of decisions made in 784d. Don't read the UMAP too literally.\n- **Cache is in `/tmp`.** Dumped on reboot, which is fine for the gallery — real applications should use a durable cache.\n\n",
    "supporting": [
      "mnist_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}