{
  "hash": "a559f3560d7906a213f29b788163b0cf",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Olivetti Faces\"\nsubtitle: \"400 face images, 64×64 grayscale, k=40 identities — 10 examples each.\"\norder: 5\nimage: olivetti-faces_files/figure-html/fig-dyf-output-1.png\ncategories: [images, small, pixels, high-k]\ntrue-k: 40\nformat:\n  html:\n    code-fold: show\n    code-tools: true\nexecute:\n  warning: false\n  message: false\n---\n\nThis is the notebook where DYF loses — and loses badly. That's why it's in the gallery. A parameter-free tool that's only shown winning is a sales pitch, not an honest benchmark.\n\nOlivetti faces is the *anti-MNIST*: small `n` (400 samples), huge `d` (4,096 pixels), high `k` (40 people, 10 photos each). Everything about it is hostile to density-based clustering. If DYF is going to break, it should break here — and understanding *why* is more valuable than pretending it doesn't.\n\n## Load the data\n\n::: {#load .cell execution_count=1}\n``` {.python .cell-code}\nfrom sklearn.datasets import fetch_olivetti_faces\n\nol = fetch_olivetti_faces()\nX = ol.data.astype(\"float32\")   # (400, 4096) — 64×64 pixel vectors\ny = ol.target                   # (400,) — 0..39, each person gets 10 photos\n\nprint(f\"{X.shape[0]} samples, {X.shape[1]}d, true k = {len(set(y))}\")\nprint(f\"Examples per class: {len(X) // len(set(y))}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n400 samples, 4096d, true k = 40\nExamples per class: 10\n```\n:::\n:::\n\n\n## Run DYF\n\n::: {#run-dyf .cell execution_count=2}\n``` {.python .cell-code}\nimport sys\nsys.path.insert(0, \".\")\nfrom _gallery import run_dyf, run_kmeans, plot_single, metrics_table\n\nresult = run_dyf(X, y)\nprint(f\"Recovered k: {result.recovered_k}  (true k = {result.true_k})\")\nprint(f\"NMI:         {result.nmi:.3f}\")\nprint(f\"ARI:         {result.ari:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRecovered k: 3  (true k = 40)\nNMI:         0.199\nARI:         0.037\n```\n:::\n:::\n\n\nThat's a blowout. DYF recovered a small handful of clusters where the ground truth has 40.\n\n## Oracle k-means\n\n::: {#kmeans .cell execution_count=3}\n``` {.python .cell-code}\nkmeans = run_kmeans(X, y)\nprint(f\"k-means NMI={kmeans['nmi']:.3f}, ARI={kmeans['ari']:.3f} (told k={result.true_k})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nk-means NMI=0.629, ARI=0.430 (told k=40)\n```\n:::\n:::\n\n\n## Figures\n\n::: {.gallery-fluid}\n\n::: {#cell-fig-truth .cell execution_count=4}\n``` {.python .cell-code}\nplot_single(result.umap_2d, y, title=f\"Ground truth (k={result.true_k})\")\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n![Ground truth — 40 people, 10 photos each.](olivetti-faces_files/figure-html/fig-truth-output-1.png){#fig-truth width=470 height=470}\n:::\n:::\n\n\n::: {#cell-fig-dyf .cell execution_count=5}\n``` {.python .cell-code}\nplot_single(result.umap_2d, result.labels, title=f\"DYF (recovered k={result.recovered_k})\")\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n![DYF — under-partitions severely.](olivetti-faces_files/figure-html/fig-dyf-output-1.png){#fig-dyf width=470 height=470}\n:::\n:::\n\n\n::: {#cell-fig-kmeans .cell execution_count=6}\n``` {.python .cell-code}\nplot_single(result.umap_2d, kmeans[\"labels\"], title=f\"k-means (told k={result.true_k})\")\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n![K-means given the oracle k=40.](olivetti-faces_files/figure-html/fig-kmeans-output-1.png){#fig-kmeans width=470 height=470}\n:::\n:::\n\n\n:::\n\n## Metrics\n\n::: {#metrics .cell execution_count=7}\n``` {.python .cell-code}\nprint(metrics_table(result, kmeans, None))\n```\n| Method | Recovered k | NMI | ARI | % discarded |\n|--------|------------:|----:|----:|------------:|\n| **DYF** (parameter-free) | 3 | 0.199 | 0.037 | 0% |\n| k-means (oracle k=40) | 40 | 0.629 | 0.430 | 0% |\n:::\n\n\n## Why DYF fails here\n\nThree things are working against it simultaneously:\n\n**1. Not enough density per latent cluster.**\nDYF's tree splits recursively while each leaf contains more than `min_leaf_size=20` points. With 40 identities and only 10 photos each, there is no way to carve out a leaf that isolates a single identity — the minimum leaf is 2× larger than any one class's support. Louvain then runs on leaf-centroid similarity and merges related leaves into a handful of coarse communities. The floor is built into the algorithm.\n\nYou can fix this by lowering `min_leaf_size`, but that's *tuning a parameter* — exactly what this gallery is showing DYF can avoid when it has enough data. The gallery's DYF defaults are deliberately never tweaked.\n\n**2. `n << d` geometry.**\n400 points living in 4,096 dimensions is an extraordinary amount of empty space. Distances lose contrast. LSH-based splits are essentially finding random hyperplanes through a void; the \"learned\" PCA directions explain little of the real variance because 400 samples can only support ~400 meaningful principal components, and most of the 4,096 dimensions are pure noise for this sample size.\n\n**3. Face-identity is a curved manifold, not a density cluster.**\nEven with unlimited photos per person, identity manifolds in raw pixel space are narrow and curved — lighting, pose, expression all move you along the manifold without changing identity. Density-based methods look for dense blobs surrounded by empty space; identity manifolds don't look like that.\n\n### What the oracle gets you\n\nK-means with `k=40` handed over hits NMI 0.629, ARI 0.430. It's a respectable number despite all the challenges — because with the oracle, k-means just has to find 40 centers. It doesn't have to discover that there *are* 40 centers. That discovery is the hard part, and it's what DYF is being asked to do unaided.\n\n### Would anything fix DYF here?\n\nYes — but the fixes are the kind of engineering work the gallery is trying to avoid as a user burden:\n\n- **Pre-embed the faces with a face-recognition model.** FaceNet / ArcFace embeddings compress each identity to a tight 128d or 512d cluster that density-based methods *can* find. This is the RAG-for-images pattern — embed with a model trained for the geometry you want, then cluster.\n- **Lower `min_leaf_size` and let Louvain over-split.** Works, but it's tuning.\n- **Use a different method.** K-means with the oracle *k* wins here, and that's fine. No tool dominates every regime.\n\n### The sports analogy\n\nIf Digits was k-means's home court and 20 Newsgroups was an away game, Olivetti is a *forfeit*. DYF didn't show up with the right equipment. It's honest to say so.\n\n## What to take away\n\n- **DYF has a floor condition: density per latent cluster.** When your data has fewer than ~`min_leaf_size × 2` samples per class, DYF will under-partition. That's the pragmatic rule.\n- **High-k / low-n is the hardest regime** for any unsupervised method. Even k-means with the oracle only hits NMI 0.63 here; without the oracle it would do worse.\n- **Dimensionality by itself isn't the problem** — 20 Newsgroups was 384d with 18K points and DYF tied k-means. `n / d` ratio and density per cluster are what matter.\n- **If you can pre-embed with a model trained on your identity axis**, the problem transforms into a geometry DYF handles well. That's the right engineering move, and it's what the DYF ecosystem is designed to compose with.\n\n## Caveats\n\n- This notebook deliberately uses raw pixels. A version with FaceNet embeddings would tell a very different story and probably match or beat k-means. The gallery shows the *default* behavior; it's not claiming DYF cannot be helped with the right upstream model.\n- Olivetti is a 1994 benchmark dataset. Modern face-identity clustering is a solved problem with pretrained embeddings; this notebook is pedagogical, not a recommendation.\n\n",
    "supporting": [
      "olivetti-faces_files"
    ],
    "filters": [],
    "includes": {}
  }
}