{
  "hash": "967c92fc370e32805e734444b61d346f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"20 Newsgroups\"\nsubtitle: \"18,846 posts, MiniLM-384d sentence embeddings, k=20 hierarchical topics.\"\norder: 4\nimage: twenty-newsgroups_files/figure-html/fig-dyf-output-1.png\ncategories: [text, medium, embeddings, hierarchical]\ntrue-k: 20\nformat:\n  html:\n    code-fold: show\n    code-tools: true\nexecute:\n  warning: false\n  message: false\n---\n\nIf Digits was k-means's home court — ten roughly-convex blobs, exactly the geometry k-means was born to carve — 20 Newsgroups is an away game. Sentence embeddings produce *curved* topic manifolds that share vocabulary at their borders: `comp.sys.ibm.pc.hardware` and `comp.sys.mac.hardware` bleed into each other; `talk.politics.mideast` and `talk.religion.misc` share a substantial amount of language. K-means has to slice straight Voronoi lines through those seams. DYF can follow the curve.\n\nThat's the prediction. Let's see whether it pans out.\n\n## Load 20 Newsgroups\n\n::: {#load .cell execution_count=1}\n``` {.python .cell-code}\nfrom sklearn.datasets import fetch_20newsgroups\n\ndata = fetch_20newsgroups(\n    subset=\"all\",\n    remove=(\"headers\", \"footers\", \"quotes\"),  # strip boilerplate so the model scores on content\n)\nprint(f\"{len(data.data):,} posts across {len(data.target_names)} classes\")\nprint(f\"Examples: {data.target_names[:4]} ...\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n18,846 posts across 20 classes\nExamples: ['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware'] ...\n```\n:::\n:::\n\n\n## Embed with MiniLM-L6-v2 (384d)\n\nSentence embeddings, not TF-IDF. This is the standard \"turn text into semantic vectors\" move and it's what downstream RAG / retrieval systems actually use. Cached to `/tmp` on first run so re-renders are cheap.\n\n::: {#embed .cell execution_count=2}\n``` {.python .cell-code}\nimport os\nimport numpy as np\nimport time\n\nCACHE = \"/tmp/twenty_ng_minilm.npz\"\n\nif os.path.exists(CACHE):\n    z = np.load(CACHE)\n    X, y = z[\"X\"], z[\"y\"]\n    print(f\"Cache hit: {X.shape[0]:,} × {X.shape[1]}d embeddings\")\nelse:\n    from sentence_transformers import SentenceTransformer\n    model = SentenceTransformer(\"sentence-transformers/all-MiniLM-L6-v2\")\n    t0 = time.time()\n    X = model.encode(data.data, show_progress_bar=False, batch_size=64)\n    X = np.ascontiguousarray(X, dtype=np.float32)\n    y = np.asarray(data.target)\n    print(f\"Embedded {X.shape[0]:,} posts in {time.time() - t0:.1f}s → {X.shape[1]}d\")\n    np.savez(CACHE, X=X, y=y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCache hit: 18,846 × 384d embeddings\n```\n:::\n:::\n\n\n## Run DYF (parameter-free)\n\nSame call as every other notebook in this gallery — no arguments tuned for text.\n\n::: {#run-dyf .cell execution_count=3}\n``` {.python .cell-code}\nimport sys\nsys.path.insert(0, \".\")\nfrom _gallery import run_dyf, run_kmeans, plot_single, metrics_table\n\nresult = run_dyf(X, y)\n\nprint(f\"Recovered k: {result.recovered_k}  (true k = {result.true_k})\")\nprint(f\"NMI:         {result.nmi:.3f}\")\nprint(f\"ARI:         {result.ari:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRecovered k: 10  (true k = 20)\nNMI:         0.472\nARI:         0.301\n```\n:::\n:::\n\n\n## Oracle k-means baseline\n\n::: {#kmeans .cell execution_count=4}\n``` {.python .cell-code}\nkmeans = run_kmeans(X, y)\nprint(f\"k-means NMI={kmeans['nmi']:.3f}, ARI={kmeans['ari']:.3f} (told k={result.true_k})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nk-means NMI=0.505, ARI=0.345 (told k=20)\n```\n:::\n:::\n\n\n## What about HDBSCAN?\n\nSkipped here. On 18,846 × 384d, HDBSCAN's defaults take ~2.5 minutes of wall clock and then flag **84% of points as noise** — it's scoring NMI on only the 16% of posts it was willing to cluster. The comparison becomes unfair in the other direction (HDBSCAN is allowed to pick its battles), and the notebook render balloons by 2+ minutes for a mostly uninformative number. The digits notebook keeps HDBSCAN because the noise fraction is small there; here it's not a useful reference.\n\n## Figures\n\nThree views of the same UMAP layout: ground-truth classes, DYF's parameter-free partition, and k-means given the oracle `k=20`.\n\n::: {.gallery-fluid}\n\n::: {#cell-fig-truth .cell execution_count=5}\n``` {.python .cell-code}\nplot_single(result.umap_2d, y, title=f\"Ground truth (k={result.true_k})\")\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n![Ground truth — 20 newsgroup classes.](twenty-newsgroups_files/figure-html/fig-truth-output-1.png){#fig-truth width=470 height=470}\n:::\n:::\n\n\n::: {#cell-fig-dyf .cell execution_count=6}\n``` {.python .cell-code}\nplot_single(result.umap_2d, result.labels, title=f\"DYF (recovered k={result.recovered_k})\")\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n![DYF — parameter-free, no k supplied.](twenty-newsgroups_files/figure-html/fig-dyf-output-1.png){#fig-dyf width=470 height=470}\n:::\n:::\n\n\n::: {#cell-fig-kmeans .cell execution_count=7}\n``` {.python .cell-code}\nplot_single(result.umap_2d, kmeans[\"labels\"], title=f\"k-means (told k={result.true_k})\")\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n![K-means given the oracle k=20.](twenty-newsgroups_files/figure-html/fig-kmeans-output-1.png){#fig-kmeans width=470 height=470}\n:::\n:::\n\n\n:::\n\n## Metrics\n\n::: {#metrics .cell execution_count=8}\n``` {.python .cell-code}\nprint(metrics_table(result, kmeans, None))\n```\n| Method | Recovered k | NMI | ARI | % discarded |\n|--------|------------:|----:|----:|------------:|\n| **DYF** (parameter-free) | 10 | 0.472 | 0.301 | 0% |\n| k-means (oracle k=20) | 20 | 0.505 | 0.345 | 0% |\n:::\n\n\n## Ten communities for twenty classes — which twenty?\n\nDYF stopped at 10. That is half the flat label's count, and it could mean two very different things: the community-detection stage under-resolved the leaf graph (as it does on [Digits](digits.qmd), a much smaller dataset), or DYF landed on a *coarser real level* of the newsgroup hierarchy. 20 Newsgroups has seven top-level buckets — `alt`, `comp`, `misc`, `rec`, `sci`, `soc`, `talk` — so the second reading is testable: score the same partition against the top-level label.\n\n::: {#top-level .cell execution_count=9}\n``` {.python .cell-code}\nfrom sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score\n\ntop_names = sorted({n.split(\".\")[0] for n in data.target_names})\ny_top = np.asarray([top_names.index(data.target_names[t].split(\".\")[0]) for t in y])\n\ndef score(lab):\n    return normalized_mutual_info_score(y_top, lab), adjusted_rand_score(y_top, lab)\n\nprint(f\"{len(top_names)} top-level groups: {top_names}\\n\")\nprint(f\"{'partition':32s}   NMI    ARI   (vs top-level label)\")\nfor name, lab in [(f\"DYF raw (k={result.recovered_k})\", result.labels),\n                  (\"k-means (told k=20)\", kmeans[\"labels\"])]:\n    n_, a_ = score(lab)\n    print(f\"{name:32s}  {n_:.3f}  {a_:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n7 top-level groups: ['alt', 'comp', 'misc', 'rec', 'sci', 'soc', 'talk']\n\npartition                          NMI    ARI   (vs top-level label)\nDYF raw (k=10)                    0.423  0.299\nk-means (told k=20)               0.426  0.214\n```\n:::\n:::\n\n\nCompare the two rows to the same methods scored against the 20-class label above. The answer is *both readings at once*. DYF's ten communities keep the top-level structure better than k-means's twenty do — ARI 0.299 vs 0.214 against the seven buckets, NMI tied — and DYF's ARI is essentially the same whether you judge it by buckets (0.299) or by the 20 classes (0.301), which is what a partition sitting between two levels of a hierarchy looks like. But NMI 0.42 against seven buckets is not a clean seven-way split either. The ten communities are coarser than the leaves and finer than the branches, and they respect the branches about as well as anything here does.\n\n## Walking down the hierarchy\n\nWhatever the reading, DYF's 10 communities are the top of a partition hierarchy that can be collapsed further:\n\n::: {#merge-walk .cell execution_count=10}\n``` {.python .cell-code}\nfrom _gallery import merge_walk, merge_walk_table\n\nwalk = merge_walk(result, X, y, targets=[25, 20, 10, 7, 4])\nprint(merge_walk_table(walk, result))\n```\n| Resolution     | Actual k | NMI   | ARI   |\n|----------------|---------:|------:|------:|\n| **Raw DYF**    | **10** | **0.472** | **0.301** |\n| merge → 25    |   10     | 0.472 | 0.301 |\n| merge → 20    |   10     | 0.472 | 0.301 |\n| merge → 10    |   10     | 0.472 | 0.301 |\n| merge → 7     |    7     | 0.420 | 0.224 |\n| merge → 4     |    4     | 0.319 | 0.127 |\n:::\n\n\nTargets above 10 are no-ops. `merge → 7` is the interesting row: seven is the number of top-level newsgroup buckets. Collapsing to it costs 0.05 NMI and 0.08 ARI against the 20-class label — a real loss, but a smaller one than k-means's twenty clusters suffer when judged at the bucket level (ARI 0.345 → 0.214 in the cell above). The coarse structure is in the tree; it is just not the level DYF stopped at.\n\n## How DYF and k-means disagree — and why\n\nCompare this to the Digits notebook:\n\n| Dataset  | k-means NMI | DYF NMI | Gap   |\n|----------|------------:|--------:|------:|\n| Digits   | 0.773       | 0.627   | 0.146 |\n| **20 Newsgroups** | **0.505** | **0.472** | **0.033** |\n\n**The gap shrank by about three-quarters.** On text, oracle-tuned k-means is a few hundredths of NMI ahead of DYF-with-no-knobs, at half the cluster count. Two things changed between the notebooks:\n\n**1. The manifold started to bend.**\nSentence embeddings for `comp.sys.ibm.pc.hardware` and `comp.sys.mac.hardware` overlap — they share vocabulary (\"driver\", \"boot\", \"RAM\"), writing style, question types. In UMAP those classes don't sit as disjoint blobs; they bleed into each other along a curved seam. K-means has to plant a Voronoi boundary *somewhere* in that seam, and wherever it plants it, it misclassifies the items near the line. DYF's density-based cut can follow the seam instead of cutting straight across it.\n\n**2. The tree is bigger.**\nDigits hands community detection ~170 leaf centroids and gets under-split to 7 for 10. Here the tree has several times as many leaves and DYF recovers 10 for 20 — still coarse, but the label it is coarse *against* is itself a two-level hierarchy, which is why the top-level cell above exists. On [MNIST](mnist.qmd) (70,000 points, thousands of leaves) the same code recovers 12 for 10. Leaf count, not sample count, is the axis to watch.\n\n### The home-court / away-game framing, continued\n\nK-means is a superb algorithm when the problem matches its inductive bias: *\"minimize within-cluster Euclidean variance, and I'll tell you how many clusters there are.\"* Digits satisfies both conditions perfectly — ten convex blobs, k handed over. Text embeddings break both conditions at once: the geometry isn't convex, and the real number of semantic communities isn't even well-defined (there are 7 top-level topic groups, 20 flat labels, and a debatable number of sub-topics).\n\nOn its home court k-means wins by 0.146 NMI. On the away game it wins by 0.033. The remaining notebooks — Olivetti Faces (40 identities, 10 examples each, *very* non-convex in pixel space) and CMU MoCap (continuous motion manifolds, no single right `k`) — push both methods into regimes where neither does well, for different reasons.\n\n### Pros and cons recap\n\n|                            | **DYF (parameter-free)**                                             | **K-means (oracle k=20)**                               |\n|----------------------------|----------------------------------------------------------------------|---------------------------------------------------------|\n| Needs `k`?                 | No.                                                                  | Yes — given 20 upfront.                                 |\n| Behavior on curved manifolds | Follows density; can trace seams.                                  | Cuts straight Voronoi lines across them.                |\n| Behavior when true structure is hierarchical | Stops at one level of it (10 here); the merge walk gives the coarser ones. | Forced to a flat 20-partition; can't express hierarchy. |\n| Behavior when embedding noise is high | Tree leaves absorb some noise before Louvain merges. | Sensitive — outliers pull centroids.                    |\n| Tree output                | Yes — can re-cut at coarser resolution post-hoc.                     | No — flat at exactly `k`.                               |\n\n## What to take away\n\n- **DYF comes within 0.03 NMI of oracle k-means on text**, without `k` and with half the clusters.\n- **The recovered 10 is coarse against the 20-class label, and half-right against the 7-bucket one.** It keeps the top-level structure better than oracle k-means's twenty clusters (ARI 0.30 vs 0.21) without being a clean seven-way split. Read the two scores together; either alone tells a tidier, wrong story.\n- **HDBSCAN doesn't scale here.** 144 seconds and 84% discarded is a dealbreaker at 18K+ documents, which is small by real-world RAG standards.\n- **Parameter-free is getting cheaper to justify.** On digits the oracle gave k-means a 0.146 NMI edge; here it bought 0.033. The cost of not knowing `k` drops as the geometry gets harder — which is the regime you're in whenever you don't already know what's in your corpus.\n- **Earlier versions of this page reported 23–34 communities** and read them as sub-topic hierarchy. That count came from a single-level Louvain in `dyf-rs` before 0.12.0 that could not merge communities (dyf `KNOWN_ISSUES.md`, issue 10); the numbers here are from the corrected optimiser.\n\n",
    "supporting": [
      "twenty-newsgroups_files"
    ],
    "filters": [],
    "includes": {}
  }
}